FROM python:3.9.6

# 작업 디렉토리를 설정합니다.
WORKDIR /code

# 필요한 패키지들을 설치합니다.
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && rm -rf /var/lib/apt/lists/*

# 프로젝트 파일들을 컨테이너에 복사합니다.
COPY . /code/

# requirements.txt 파일을 설치합니다.
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

# Django 애플리케이션을 실행하는 명령어를 설정합니다.
CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]