# Generated by Django 4.2.16 on 2024-11-01 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('friendship_app', '0002_alter_friendship_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='receiver_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_receiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='requester_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_requester', to=settings.AUTH_USER_MODEL),
        ),
    ]
