# Generated by Django 4.2.16 on 2024-11-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship_app', '0003_alter_friendship_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='receiver_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='friendship',
            name='requester_id',
            field=models.IntegerField(),
        ),
    ]
