# Generated by Django 4.2.16 on 2024-11-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication_app', '0004_alter_customuser_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='display_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
